config/routes.rb
Rails.application.routes.draw do
  root to: 'users#new'

  get 'register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/sign_in', to: 'sessions#create'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/search', to: 'users#search'

  resources :users, only: [:index, :show, :create, :edit, :update, :new, :search] do
    collection do
    post :search, to: "users#search"
    end
  end
  resources :departments, only: [:index, :show, :create, :edit, :update, :new]
  resources :categories, only: [:index, :show, :create, :edit, :update, :new]

  

end

app/models/categories_user.rb
class CategoriesUser < ActiveRecord::Base
	belongs_to :user
	belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :categories_users
 	has_many :users, through: :categories_users
end

app/models/department.rb
class Department < ActiveRecord::Base
	has_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
	belongs_to :department
  has_many :categories_users
  has_many :categories, through: :categories_users
	has_secure_password validations: false

	validates :au_user_name, presence: true
  validates :au_user_name, uniqueness: true
	validates :password, presence: true, on: :create, length: {minimum: 3}

  def self.search_by_last_name(search_term)

    return [] if search_term.blank?
    #binding.pry
    where("last_name LIKE ?", "%#{search_term}%")
    #binding.pry
    #return @result
  end

end


 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
  	 @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
  	!!current_user
  end

  def require_user
    if !logged_in?
      flash[:error] = "Must be logged in to do that."
      redirect_to sign_in_path
    end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index

    @category = Category.order("list_order ASC")
    
  end

  def show
    @category = Category.new
  end

  def new
    @category = Category.new
    
  end

  def create
    #binding.pry
    @category = Category.new(category_params)
     

    if @category.save
      flash[:notice] = "The category was created."
      redirect_to category_path
    else
      render 'new'
    end 
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
     
    @category = Category.find(params[:id])
    if @category.update_attributes(category_params)

      flash[:notice] = "Your category name or list order was updated."
      redirect_to category_path
    else
      render 'edit'
    end
  end

  private
    def category_params
      params.require(:category).permit!
    end
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController

  def index

    @department = Department.order("list_order ASC")
    
  end

  def show
    @department = Department.new
  end

  def new
    @department = Department.new
    
  end

  def create
    #binding.pry
    @department = Department.new(department_params)
     

    if @department.save
      flash[:notice] = "The department was created."
      redirect_to new_department_path
    else
      render 'new'
    end 
  end

  def edit
    @department = Department.find(params[:id])
  end

  def update
     
    @department = Department.find(params[:id])
    if @department.update_attributes(department_params)

      flash[:notice] = "Your department name or list order was updated."
      redirect_to new_department_path
    else
      render 'edit'
    end
  end

  private
    def department_params
      params.require(:department).permit!
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    
  end

  def create
    user = User.find_by(au_user_name: params[:username])
    #binding.pry
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "You've logged in!"
      redirect_to root_path
    else
      flash[:error] = "There is something wrong with your username or password."
      redirect_to register_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You are logged out."
    redirect_to register_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  #before_action :require_user, except: [:login]

  def index

    @users = User.all
    
    
  end

  def show
    @user = User.find(params[:id])
     #render json: @user


  end

  def new
    @user = User.new
    
  end

  def create
    @user = User.new(user_params)
    binding.pry
    if @user.save
      redirect_to sign_in_path
    else
      render :new
    end
  end 

  def edit
    @user = User.find(params[:id])
  end

  def update
     #params[:user][:category_ids] ||= []
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      AppMailer.welcome_email(@user).deliver
      flash[:notice] = "Your user profile was updated."
      redirect_to user_path
    else
      render 'edit'
    end
  end

  def delete
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id]).destroy
    flash[:notice] = "'{@user.last_name, @user.first_name}' destroyed successfully."
    redirect_to(:action => 'index')
  end

  def search
    @results = User.search_by_last_name(params[:search_term])
  end

  private

  def user_params    
    params.require(:user).permit(:au_user_name, :password, :first_name, :middle_name, :last_name, 
      :email, :category_ids, :department_id)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_form.html.erb
<%  if @category.errors.any? %>
<div class="alert alert.error">
  <h5>There were some errors!</h5>
    <ul>
      <%  @category.errors.full_messages.each do |msg| %>
      <li><%  msg %></li>
      <%  end %>
    </ul>
</div>
<%  end %>


<%= form_for @category do |f| %>
<div class="well control-group">
     
 
  <%= f.label :name, 'Rank name' %>
  <%= f.text_field :name, :size => 15, autofocus: true %><br>

  <%= f.label :list_order, 'List order' %>
  <%= f.text_field :list_order %><br>

   </div>

  <%= f.submit(@category.new_record? ? 'Create Category' : 'Update Category', class: 'btn btn-primary') %>

<% end %>

app/views/categories/edit.html.erb
<%= render 'shared/content_title', title: 'Edit this Category' %>

<%= render 'form' %>

app/views/categories/index.html.erb
<%= render 'shared/content_title', title: 'All Categories' %>

 <%# Category.all.each do |category| %>
   <!--  <li>
   		<%# link_to category.name, category_path(category) %>
   	</li> -->
 <%# end %>

<%# Category.all.each do |d| %>
    	<!-- <li>
    		 <%# d.name %>, <%# d.list_order %>,  

    	</li> -->
<%# end %>

<div style="margin-top: 1em;">
<% @category.each do |category| %> 
	<div class="row" style="margin-bottom: .5em;">
		<div class="col-md-3"> 
			 <%= category.name %> | <%= category.list_order %>  
		</div>		
			<div class="col-lg-3">
				<%= link_to edit_category_path(category) do %>
				<div class="btn btn-warning"><i class="glyphicon glyphicon-pencil"></i> </div>
				<% end %>
			</div>		
	</div>
<% end %>
</div>

app/views/categories/new.html.erb
<%= render 'shared/content_title', title: 'Create a new Person' %>
<%= render 'form' %>

app/views/categories/show.html.erb
<%= render 'shared/content_title', title: 'All Categories' %>

 

 

app/views/departments/_form.html.erb
<style type="text/css">
label { display: block;}
input { margin-bottom: 20px;}
</style>
<%  if @department.errors.any? %>
<div class="alert alert.error">
	<h5>There were some errors!</h5>
		<ul>
			<%  @department.errors.full_messages.each do |msg| %>
			<li><%  msg %></li>
			<%  end %>
		</ul>
</div>
<%  end %>


<%= form_for @department do |f| %>
<div class="well control-group">
	   
 
	<%= f.label :name, 'Department name' %>
	<%= f.text_field :name, :size => 15, autofocus: true %><br>

	<%= f.label :list_order, 'List order' %>
	<%= f.text_field :list_order %><br>

	 </div>

	<%= f.submit(@department.new_record? ? 'Create Department' : 'Update Department', class: 'btn btn-primary') %>

<% end %>

app/views/departments/edit.html.erb
<%= render 'shared/content_title', title: 'Edit this Department' %>

<%= render 'form' %>

app/views/departments/index.html.erb
<%= render 'shared/content_title', title: 'All Departments' %>

 <%# Department.all.each do |department| %>
   <!--  <li>
   		<%# link_to department.name, department_path(department) %>
   	</li> -->
 <%# end %>

<%# Department.all.each do |d| %>
    	<!-- <li>
    		 <%# d.name %>, <%# d.list_order %>,  

    	</li> -->
<%# end %>



<div style="margin-top: 1em;">
<% @department.all.each do |department| %> 
	<div class="row" style="margin-bottom: .5em;">
		<div class="col-md-3"> 
			 <%= department.name %> | <%= department.list_order %>  
		</div>		
			<div class="col-lg-3">
				<%= link_to edit_department_path(department) do %>
				<div class="btn btn-warning"><i class="glyphicon glyphicon-pencil"></i> </div>
				<% end %>
			</div>		
	</div>
<% end %>
</div>

app/views/departments/new.html.erb
<%= render 'shared/content_title', title: 'Add new department' %>

<%= render 'form' %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
      <%= link_to "PeopleKeeper", root_path, :class => 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if logged_in? %>
        <li > <%= link_to "Departments", departments_path %></li>
        <li > <%= link_to "Categories", categories_path %></li>
        <li > <%= link_to "Search", search_path %></li> 

         
         <li><a >Hi <%= current_user.au_user_name %></a></li>
         <li>
          <%= link_to 'Log out', logout_path %>
          </li>
          <% else %>
          <li>
            <%= link_to 'Register', register_path %>
          </li>
          <li>
            <%= link_to 'Log in', login_path %>
            <% end %>
          </li>

      </ul>       
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

 

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>People Keeper</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js">    
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
         <div class="row">
          <div class="col-md-12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/people/_form.html.erb
<%  if @user.errors.any? %>
<div class="alert alert.error">
  <h5>There were some errors!</h5>
    <ul>
      <%  @user.errors.full_messages.each do |msg| %>
      <li><%  msg %></li>
      <%  end %>
    </ul>
</div>
<%  end %>


<%= form_for @user do |f| %>
<div class="well control-group">
<div class="row">
  <div class="col-md-6">

    <%=  f.label "Select a department" %>    
    <%= f.select("department_id", Department.all.collect {|d| [ d.name, d.id ] }, {include_blank: 'None'}) %>
    <br /><br />
  
 
  <%= f.label :first_name, 'First name' %>
  <%= f.text_field :first_name, :size => 15, autofocus: true %><br>

  <%= f.label :middle_name, 'Middle name' %>
  <%= f.text_field :middlename %><br>

  <%= f.label :last_name, 'Last name' %>
  <%= f.text_field :lastname %><br>

  <%= f.label :email %>
  <%= f.text_field :email, :size => 30, :placeholder => '@auburn.edu' %>

   

  <%= f.label :au_user_name, 'AU user name' %>
  <%= f.text_field :au_user_name %>

  <%= f.label :office_address, 'Office address' %>
  <%= f.text_field :office_address %>

  <%= f.label :phone %>
  <%= f.text_field :phone %>

  <%= f.label :interest_areas, 'Interest areas' %>
  <%= f.text_area :interest_areas %>

  <%= f.label :instructional_areas, 'Instructional areas' %>
  <%= f.text_field :languagestaught %>
  <fieldset>
    <legend>Office Hours</legend>
      <%= f.label :monday_hours %>
      <%= f.text_field :monday_hours, :size => 30 %>

      <%= f.label :tuesday_hours %>
      <%= f.text_field :tuesday_hours, :size => 30 %>

      <%= f.label :wednesday_hours %>
      <%= f.text_field :wednesday_hours, :size => 30 %>

      <%= f.label :thursday_hours %>
      <%= f.text_field :thursday_hours, :size => 30 %>

      <%= f.label :friday_hours %>
      <%= f.text_field :friday_hours, :size => 30 %>
  </fieldset> 
  </div>  
<div class="col-md-6">
   
      <%= collection_check_boxes(:user, :category_ids, Category.all, :id, :name) %>
   
 </div>
</div>
</div>

  <%= f.submit(@user.new_record? ? 'Create User' : 'Update User', class: 'btn btn-primary') %>

<% end %>

app/views/people/edit.html.erb
<%= render 'shared/content_title', title: 'Edit this person' %>

<%= render 'form' %>

app/views/people/index.html.erb
<%= render 'shared/content_title', title: 'People Keeper' %>
 

<%= link_to 'Add new person', new_person_path, class: 'btn btn-success' %>

<div style="margin-top: 1em;">
<% @people.each do |person| %> 
	<div class="row" style="margin-bottom: .5em;">
		<div class="col-md-3"> 
			 <%= person.lastname %>, <%= person.firstname %> <%= person.middlename %>
		</div>		
			<% if logged_in? %>
			<div class="col-md-1">
				<%= link_to edit_person_path(person) do %>
				<div class="btn btn-warning"><i class="glyphicon glyphicon-pencil"></i> </div>
				<% end %>
			</div>	
			<% end %>	
		<div class="col-md-1">
				<%= link_to edit_person_path(person) do %>
				<div class="btn btn-danger"><i class="glyphicon glyphicon-trash"></i> </div>
				<% end %>
			</div>			
	</div>
<% end %>
</div>

app/views/people/new.html.erb
<%= render 'shared/content_title', title: 'Create a new Person' %>
<%= render 'form' %>

app/views/people/show.html.erb
<%= render 'shared/content_title', title: 'Show' %>

app/views/shared/_content_title.html.erb
<p class="lead">
	<%= title %>
	<hr />
</p>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="alert alert.error">
      <h5>There were some errors! Please fix them.</h5>
      <ul>
        <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %> 
      </ul>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<div class="well">
  <%= form_for @user do |f| %>
    <%= render 'shared/errors', obj: @user %>
    <div class="control-group">
      <%= f.label :au_user_name %>
      <%= f.text_field :au_user_name %>
    </div>

    <div class="control-group">
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>
    <%= f.submit @user.new_record? ? "Register" : "Update Profile", class: 'btn btn-success' %>

  <% end %>
</div>

app/views/users/_form_full.html.erb
<style type="text/css">
label { display: block;}
input { margin-bottom: 20px;}
</style>
<%  if @user.errors.any? %>
<div class="alert alert.error">
  <h5>There were some errors!</h5>
    <ul>
      <%  @user.errors.full_messages.each do |msg| %>
      <li><%  msg %></li>
      <%  end %>
    </ul>
</div>
<%  end %>


<%= form_for @user do |f| %>
<div class="well control-group">
<div class="row">
  <div class="col-md-6">

    <%=  f.label "Select a department" %>    
    <%= f.select("department_id", Department.all.collect {|d| [ d.name, d.id ] }, {include_blank: 'None'}) %>
    <br /><br />
  
 
  <%= f.label :first_name, 'First name' %> 
  <%= f.text_field :first_name, :size => 15, autofocus: true %> 

  <%= f.label :middle_name, 'Middle name' %> 
  <%= f.text_field :middle_name %> 

  <%= f.label :last_name, 'Last name' %> 
  <%= f.text_field :last_name %> 

  <%= f.label :email, 'Email address' %> 
  <%= f.text_field :email, :size => 25, :placeholder => '@auburn.edu' %> 

   

  <%= f.label :au_user_name, 'AU user name' %>
  <%= f.text_field :au_user_name %>

  <%= f.label :office_address, 'Office address' %>
  <%= f.text_field :office_address %>

  <%= f.label :phone %>
  <%= f.text_field :phone %>

  <%= f.label :interest_areas, 'Interest areas' %>
  <%= f.text_area :interest_areas %>

  <%= f.label :instructional_areas, 'Instructional areas' %>
  <%= f.text_field :instructional_areas %>
  <fieldset>
    <legend>Office Hours</legend>
      <%= f.label :monday_hours %>
      <%= f.text_field :monday_hours, :size => 30 %>

      <%= f.label :tuesday_hours %>
      <%= f.text_field :tuesday_hours, :size => 30 %>

      <%= f.label :wednesday_hours %>
      <%= f.text_field :wednesday_hours, :size => 30 %>

      <%= f.label :thursday_hours %>
      <%= f.text_field :thursday_hours, :size => 30 %>

      <%= f.label :friday_hours %>
      <%= f.text_field :friday_hours, :size => 30 %>
  </fieldset> 
  </div>  
<div class="col-md-6">
   
      <%= collection_check_boxes(:user, :category_ids, Category.all, :id, :name) %>
   
 </div>
</div>
</div>

  <%= f.submit(@user.new_record? ? 'Create User' : 'Update User', class: 'btn btn-primary') %>

<% end %>

app/views/users/edit.html.erb
<h4>Edit a your profile</h4>
<%= render 'form_full' %>

app/views/users/index.html.erb
<%= render 'shared/content_title', title: 'People Keeper (index)' %>
 

<%= link_to 'Add new user', new_user_path, class: 'btn btn-success' %>

<div style="margin-top: 1em;">
<% @users.each do |user| %> 
  <div class="row" style="margin-bottom: .5em;">
    <div class="col-md-3"> 
       <%= user.last_name %>, <%= user.first_name %> <%= user.middle_name %>
    </div>    
      <% if logged_in? %>
      <div class="col-md-1">
        <%= link_to edit_user_path(user) do %>
        <div class="btn btn-warning"><i class="glyphicon glyphicon-pencil"></i> </div>
        <% end %>
      </div>  
      <% end %> 
    <div class="col-md-1">
        <%= link_to edit_user_path(user) do %>
        <div class="btn btn-danger"><i class="glyphicon glyphicon-trash"></i> </div>
        <% end %>
      </div>      
  </div>
<% end %>
</div>

app/views/users/new.html.erb
<h4>Register a user</h4>
<%= render 'form_full' %>

app/views/users/search.html.erb
  <%= render 'shared/content_title', title: 'Search by last name' %>
  or <%= link_to 'Add new user', new_user_path, class: 'btn btn-success' %>
 <%= form_tag search_users_path, class: "col_md_5 navbar-form for-search" do  %>
      <div class="form-group">
        <%= text_field_tag :search_term,  'Search by lastname', class: 'form-control'  %>
      <%= button_tag  'Search', class: 'button btn btn-default' %>

    </div>
   <% end %>

  


 



<div style="margin-top: 1em;">
<% @results.each do |result| %> 
  <div class="row" style="margin-bottom: .5em;">
    <div class="col-md-3"> 
       <%= result.last_name %>, <%= result.first_name %> <%= result.middle_name %>
    </div>    
      <% if logged_in? %>
      <div class="col-md-1">
        <%= link_to edit_user_path(result) do %>
        <div class="btn btn-warning"><i class="glyphicon glyphicon-pencil"></i> </div>
        <% end %>
      </div>  
      <% end %> 
    <div class="col-md-1">
        <%= link_to edit_user_path(result) do %>
        <div class="btn btn-danger"><i class="glyphicon glyphicon-trash"></i> </div>
        <% end %>
      </div>      
  </div>
<% end %>
</div>


    

app/views/users/show.html.erb
<%= render 'shared/content_title', title: 'Show' %>

 <%= @user.first_name%> <%= @user.last_name %>